### ISSUE TITLE
pyopengl/project 1/Assets/models lost

### ISSUE THREAD

**Issue by PaaavelZ** [amengede/getIntoGameDev#5]
Hello, guy! In your guide [Gamedev Project 1: Coding (Python)](https://www.youtube.com/watch?v=-aSCDqtaif4&list=PLn3eTxaOtL2PDnEVNwOgZFm5xYPr4dUoR&index=9) you used a `models` folder and, unfortunately, in the current repo there is not. The game doesn't run without that folder. So, can you please download it again? I see that folder was in repo for [commit](https://github.com/amengede/getIntoGameDev/commit/f29b9bd3e4add6ff7d6bc3bf92db8ba0a9ff093c), but now it has disappeared.

**Comment by amengede** [comment]
The models are in the Assets/models folder at the top level of the repo. Hope that helps!

**Comment by amengede** [comment]
see previous comment.
